package net.nicotfpn.alientech.screen;

import com.mojang.blaze3d.systems.RenderSystem;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.renderer.GameRenderer;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.player.Inventory;
import net.nicotfpn.alientech.client.gui.AlienScreen;
import net.nicotfpn.alientech.AlienTech;

/**
 * GUI Screen for Ancient Battery.
 * Features:
 * - Top Slot: Output (Charge Item)
 * - Bottom Slot: Input (Discharge Item)
 * - Center: Giant Energy Bar
 */
public class AncientBatteryScreen extends AlienScreen<AncientBatteryMenu> {

    // Points to the texture generated by the Java program
    private static final ResourceLocation TEXTURE = ResourceLocation.fromNamespaceAndPath(
            AlienTech.MOD_ID, "textures/gui/ancient_battery_gui.png");

    public AncientBatteryScreen(AncientBatteryMenu menu, Inventory playerInventory, Component title) {
        super(menu, playerInventory, title);
    }

    @Override
    protected void init() {
        super.init();
        this.imageWidth = 176;
        this.imageHeight = 166;
        this.inventoryLabelY = 10000; // Hide default labels
        this.titleLabelY = 10000;
    }

    @Override
    protected void addGuiElements() {
        // No standard elements for now, implementing custom giant bar in render
    }

    @Override
    protected void drawBackgroundTexture(GuiGraphics guiGraphics, int x, int y) {
        RenderSystem.setShader(GameRenderer::getPositionTexShader);
        RenderSystem.setShaderColor(1.0F, 1.0F, 1.0F, 1.0F);

        // 1. Draw the main background (which already includes blue slots and black
        // battery background)
        // Texture coordinates 0,0
        guiGraphics.blit(TEXTURE, x, y, 0, 0, imageWidth, imageHeight, 256, 256);

        // 2. Draw the Giant Energy Bar Fill
        // Screen position: x=66, y=14. Total size: 44x60.
        drawGiantEnergyBarFill(guiGraphics, x + 66, y + 14, 44, 60);
    }

    private void drawGiantEnergyBarFill(GuiGraphics guiGraphics, int x, int y, int width, int height) {
        int max = menu.getMaxEnergy();
        int stored = menu.getEnergyStored();

        // Useable inner height (discounting 1 pixel border top and bottom)
        int innerHeight = height - 2;
        int innerWidth = width - 2;

        // Calculate how many pixels high the fill should be
        int fillHeight = max > 0 ? (int) ((long) stored * innerHeight / max) : 0;

        // Safety cap
        if (fillHeight > innerHeight)
            fillHeight = innerHeight;

        if (fillHeight > 0) {
            int textureInnerU = 177;
            int fullInnerHeight = 58; // 60 - 2
            int textureVOffset = (fullInnerHeight - fillHeight);
            int textureCurrentV = 1 + textureVOffset;

            // Draw from bottom up
            int screenY = y + height - 1 - fillHeight;

            guiGraphics.blit(TEXTURE,
                    x + 1, // Screen X (inside border)
                    screenY, // Screen Y (top of current level)
                    textureInnerU, // Texture U (start of green)
                    textureCurrentV, // Texture V (top of green slice)
                    innerWidth, // Width
                    fillHeight, // Height
                    256, 256);
        }
    }

    @Override
    protected void renderLabels(GuiGraphics guiGraphics, int mouseX, int mouseY) {
        // Title in Egyptian Gold
        int titleX = (imageWidth - font.width(title)) / 2;
        guiGraphics.drawString(font, title, titleX, 4, 0xD4AF37, false);

        // Player Inventory Title (standard dark gray)
        guiGraphics.drawString(font, this.playerInventoryTitle, 8, this.imageHeight - 96 + 2, 4210752, false);

        // NOTE: Do NOT call renderTooltip here. renderLabels has a translation
        // matrix applied (leftPos, topPos), which causes tooltip coordinates
        // to be double-offset when using absolute mouseX/mouseY.
    }

    @Override
    public void render(GuiGraphics guiGraphics, int mouseX, int mouseY, float partialTick) {
        super.render(guiGraphics, mouseX, mouseY, partialTick);
        renderTooltip(guiGraphics, mouseX, mouseY);

        // Custom tooltips — rendered here (after super.render) where coordinates
        // are in absolute screen space, so tooltips appear exactly at the cursor.
        int relX = mouseX - getGuiLeft();
        int relY = mouseY - getGuiTop();

        // Energy bar tooltip
        if (relX >= 66 && relX < 66 + 44 && relY >= 14 && relY < 14 + 60) {
            String energyText = String.format("%,d / %,d FE", menu.getEnergyStored(), menu.getMaxEnergy());
            guiGraphics.renderTooltip(font, Component.literal(energyText), mouseX, mouseY);
        }
        // Slot Charge tooltip
        if (relX >= 26 && relX < 26 + 18 && relY >= 20 && relY < 20 + 18) {
            if (!menu.getSlot(0).hasItem())
                guiGraphics.renderTooltip(font, Component.literal("Charge Item"), mouseX, mouseY);
        }
        // Slot Discharge tooltip
        if (relX >= 26 && relX < 26 + 18 && relY >= 50 && relY < 50 + 18) {
            if (!menu.getSlot(1).hasItem())
                guiGraphics.renderTooltip(font, Component.literal("Discharge Item"), mouseX, mouseY);
        }
    }
}
